config/routes.rb
Kateco::Application.routes.draw do
  
  
  devise_for :users
  resources :manufacturers
  root "manufacturers#index", as: 'home'    
  get "/about", to: "pages#about", as: "about"
  resources "contacts", only: [:new, :create]
  resources :admin
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "katecomarketinggroup@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
 end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:email]
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!
  
  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    @manufacturer.save
    redirect_to new_manufacturer_path
  end
  
  def index
    @manufacturers = Manufacturer.all.order(:sort_letter) 
    
end


  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id]) 
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
  if @manufacturer.update_attributes(manufacturer_params)
    redirect_to :action => 'show', :id => @manufacturer
  else
    render 'edit'
    end
  end


  def destroy
    @manufacturer = Manufacturer.find(params[:id])
  end




private

  
  
  def manufacturer_params
    params.require(:manufacturer).permit(:name, :summary, :composite_url, :logo_url, :company_url, :contact, :contact_email, :contact_phone, :sorting_letter) 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end
  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = "Cannot send message."
      render :new
    end
  end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    @manufacturer.save
    redirect_to new_manufacturer_path
  end
  
  def index
    @manufacturers = Manufacturer.all.order(:sort_letter)  
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
  if @manufacturer.update_attributes(manufacturer_params)
    redirect_to :action => 'show', :id => @manufacturer
  else
    render 'edit'
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    @manufacturer.destroy

    redirect_to home_path
  end


private

  
  
  def manufacturer_params
    params.require(:manufacturer).permit(:name, :summary, :composite_url, :logo_url, :company_url, :contact, :contact_email, :contact_phone, :sort_letter ) 
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    
  end
end

private

def user_params
  params.require(:user).permit(:name, :email, :password, :confirm_password)
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | Kateco"      
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/email_helper.rb
module EmailHelper
  def line_break(s)
    s.gsub("\n", "<br/>") 
  end
end

app/helpers/factory_contacts_helper.rb
module FactoryContactsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_form.html.erb
<%= simple_form_for @manufacturer do |m| %>

  <%= m.input :name %>
  <%= m.input :summary %>
  <%= m.input :composite_url %>
  <%= m.input :logo_url %>
  <%= m.input :company_url %>
  <%= m.input :contact %>
  <%= m.input :contact_email %>
  <%= m.input :contact_phone %>
  <%= m.input :sort_letter %>
  <%= m.submit "submit", class: "btn btn-primary" %>
  <% end %>
 

app/views/admin/auth.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <% if current_user %>
Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout' %>
<% else %>
<%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
<% end %>

app/views/admin/create.html.erb
<%= render "form" %>

app/views/admin/edit.html.erb
<%= render "form" %>

app/views/admin/index.html.erb
<% title("Admin Page") %>
<p>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.name.titleize %>. |  <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %> </strong></p>
  
</p>
<% end %>
<div class="row">

<% @manufacturers.each do |m| %>
  <div class="col-m-2 offset-m-2"> 
    <%= image_tag(m.logo_url, class: "img-center", width: '80%') %>
  </div>
    <div class-"col-m-4">
      <h3><%= m.name%></h3>
      <p><strong>Contact:</strong> <%= m.contact %><br>
      <strong>Email:</strong> <%= m.contact_email %><br>
      <strong>Phone:</strong> <%= m.contact_phone %><br>
      <strong>website:</strong> <%= m.company_url %><br></p>
      <p> Composite is at <%= m.composite_url %>, logo <%= m.logo_url %></p>
    </div>
    <div class="row">
      <div class="col-m-5 offset-m-3">
        <div class="summary"><%= sanitize m.summary %>
        <p>Order: <%= m.sort_letter %></p>
        </div>
      </div>
       <p> <%= link_to 'Edit', edit_manufacturer_path(m) %> | <%= link_to "Delete", manufacturer_path(m), method: :delete, data: { confirm: 'Are you sure?'} %> </p><br><br>
    </div>
<% end %>
    <%= link_to "Add a new company", new_manufacturer_path %>

app/views/admin/new.html.erb
<%= render "form" %>

app/views/admin/show.html.erb
<div class="row">
  <div class="col-xs-4 offset-xs-4">
    <div class="alert alert-dismissable" role="alert">
      
    <%= image_tag @manufacturer.logo_url, width: "250", class: "img-center" %>
  
    <h2 class="center-text"><%= link_to "Go to the #{@manufacturer.name} Website", @manufacturer.company_url, target: "blank" %></h2>
  
    <h3 class="center-text">Your contact: <%= @manufacturer.contact %><br>
      Email: <%= @manufacturer.contact_email %><br>
      Phone: <%= @manufacturer.contact_phone %></h3>
    </div>
  </div>
</div>  
<div class="center-text">
<%= link_to "<<Home page", home_path %></div>

app/views/admin/update.html.erb
<%= render 'form' %>

app/views/contacts/create.html.erb
<div class="row">
<div class="col-s-8 offset-m-2 text-center">
<h1> Thank you for your message.</h1>
<p> We'll get back to you soon.
<br>
<br>
<strong><%=link_to "<<Back to Home page", home_path %></strong></p>
</div>
</div>

   

app/views/contacts/new.html.erb
<% title("Contact us") %>
<div class="row">
  <div class="col-s-8 offset-s-2 text-center">
  
    <h2>Send us an email</h2>
    <%= simple_form_for @contact, :html => {:class => 'form-horizontal'} do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => false, :input_html => {:rows => 10} %>
      <div class="hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div class="form-actions">
      <%= f.button :submit, 'Send message', :class => "btn btn-primary" %>
      </div>
    <% end %>
      <br>
    <h3> Call Kate at 425.412.0825
    </h3><br>
    <p><strong><%= link_to "<<Back to Home page", home_path %></strong></p>
  </div>
  </div>

app/views/layouts/_footer.html.erb
<div class="row voffset30"> 
  <div class="col-s-12 text-center">
  <hr>
    <p><small>&copy; 2015 Kateco Marketing Group</small></p>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="header">
  <%= image_tag("http://goo.gl/093O9V?gdriveurl", width: "175", class: "img-center") %>
</div>  
      

app/views/layouts/_nav.html.erb
  <div class="row"> 
      <div class="col-m-3 offset-m-8">
        <p><strong>
        <%= link_to "About us", about_path %>  | 
        <%= link_to "Contact us", new_contact_path %> 
        </strong></p>
      </div>
  </div>
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><%= @title || "Kateco" %></title>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true %>
    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css"> -->
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <meta name="google-site-verification" content="FKZjoLcPXo7UAFGevNN6dQWAXHaNXgykNTtdxQ_2fY0" />
</head>
<body>
<div class="page">
  <div class="body-container-fluid">
    <%= render 'layouts/header' %>
    <%= render 'layouts/nav' %>
      <div>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      </div>
  <%= yield %>
  <%= render 'layouts/footer' %>    
  </div>
</div>
  <!--<script src="vendor/jquery-2.1.3.min.js"></script>
  <script src="responsive.min.js"></script>-->
</body>
</html>

app/views/manufacturers/_form.html.erb
<%= simple_form_for @manufacturer do |m| %>

  <%= m.input :name %>
  <%= m.input :summary %>
  <%= m.input :composite_url %>
  <%= m.input :logo_url %>
  <%= m.input :company_url %>
  <%= m.input :contact %>
  <%= m.input :contact_email %>
  <%= m.input :contact_phone %>
  <%= m.submit "submit", class: "btn btn-primary" %>
  <% end %>
 

app/views/manufacturers/_modal.html.erb
<div class="modal">
  <div class="alert alert-dismissable" role="alert">
  <div class="modal-content">
    <%= image_tag m.logo_url, width: "250", class: "image-center" %>
  
    <h2><%= link_to "#{m.name} Website", m.company_url, target: "blank" %></h2>
   
  
    <h3>Your contact: <%= m.contact %><br>
      Email: <%= m.contact_email %><br>
      Phone: <%= m.contact_phone %></h3>
  </div>
  </div>
</div>

app/views/manufacturers/index.html.erb
<% title("Home Page") %>

<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Helping professionals with their<br> promotional and marketing needs<br><br></h1>
  </div>     
</div>

<div class="clearall"></div>

<div class="block-row-m-4">
  <% @manufacturers.each do |m| %>
    <div class="col-m-3" id="showcase"><br>
      <%= image_tag(m.logo_url, class: "img-center", width: '80%') %><br>
      <%= image_tag(m.composite_url, width: '100%') %>
    </div>
    <div class="col-m-3" id="showcase">
      <h2><%= m.name %></h2>
        <%= sanitize m.summary %>
        <p class="link"> <%= link_to 'Your Contacts', manufacturer_path(m) %></p>
     </div>
  <% end %>
  </div>
<div class="clearall"></div>

app/views/manufacturers/show.html.erb
<div class="row">
  <div class="col-m-6 offset-m-3">
    <div class="alert alert-dismissable" role="alert">
      
    <%= image_tag @manufacturer.logo_url, width: "250", class: "img-center" %>
  
    <h2 class="center-text"><%= link_to "Go to the #{@manufacturer.name} Website", @manufacturer.company_url, target: "blank" %></h2>
    <p>Your contact:</p>
    <h3 class="center-text"><%= @manufacturer.contact %><br>
      <%= @manufacturer.contact_email %><br>
      <%= @manufacturer.contact_phone %></h3>
    </div>
  </div>
</div>  
<div class="center-text">
<%= link_to "<<Home page", home_path %></div>

app/views/manufacturers/update.html.erb
<%= render "form" %>

app/views/pages/about.html.erb
<% title("About us") %>

  <div class="row">
    <div class="col-s-4 offset-s-2">
      <%= image_tag "https://s3-us-west-2.amazonaws.com/kateco/Kat%26Fam.png", class: "img-responsive" %>
    </div>
    <div class="col-s-4">
      <h3> About Kateco </h3> 
      <p>Kate Connolly has made her career in the promotional marketing industry since 1995 and has initiated Kateco Marketing Group to represent some of the finest manufacturers in the field.</p>

      <p>Kate is service minded, has lots of product knowledge and a "let's get it done" attitude. When she's not hard at work she's hard at play with her husband, Scott, and their daughter, Destin, loving life in Seattle.
         </p>
         <div voffset-30>
        <p><strong><%= link_to "<<Home", home_path %>  </strong></p>  
    </div>
  </div> 
</div>

app/views/pages/contact_us.html.erb
<% title("Contact us") %>
<div class="row">
  <div class="col-sm-8 col-sm-offset-2 text-center">
    <h1><br>Helping professionals with their promotional and marketing needs</h1><br>
    <%= simple_form_for @user, :html => {:class => 'form-horizontal'} do |f| %>
      <%= f.input :name, :required => true %>
      <%= f.input :email, :required => true %>
      <%= f.input :message, :as => :text, :required => false, :input_html => {:rows => 10} %>
      <div class="hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
      </div>
      <div class="form-actions">
      <%= f.button :submit, 'Send message', :class => "btn btn-primary" %>
    <% end %>
    </div>
    <h3> Call Kate at 425.412.0825
    </h3><br>
    <p><strong><%= link_to "<<Back to Home page", root_path %></strong></p>
</div>

</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

app/views/we_mail_out/sample_email.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content='text/html; charset=UTF-8' http-equiv='Content-Type' />
  </head>
  <body>
    <h1>Hi <%= @user.name %></h1>
    <p>
      Sample mail sent using smtp.
    </p>
  </body>
</html>

app/views/we_mail_out/sample_mail.text.erb
Hi <%= @user.name %>
Sample mail sent using smtp.